<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <ul>
                <li><a href="#">Дизайнерам</a></li>
            </ul>
        </div>
    </div>
</div>
<section id="designer">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6 col-xs-12 designer-item">
                <img src="img/img1.jpg" alt="">
            </div>
            <div class="col-md-6 col-md-pull-6 col-xs-12">
                <h1 class="heading">Дизайнерам и&nbsp;архитекторам</h1>
                <ul>
                    <li>индивидуальная программа сотрудничества;</li>
                    <li>подбор индивидуальной коллекции обивочных материалов (тканей, кожзама, кожи);</li>
                    <li>разработка индивидуальных объектов мебели, барных стоек, а также аксессуаров под заданный проект;</li>
                    <li>сопровождения сделок (коммерческое предложение, дизайн-проект, сертификаты на продукцию и т. д.);</li>
                    <li>предоставление образцов материалов, каталогов и других маркетинговых инструментов.</li>
                </ul>
                <a href="#" class="button">скачать каталог</a>
            </div>
        </div>
    </div>
</section>