<?php
/** @var Core\Entity\OurWork $work */
$work = $this->work;
?>
<h1 class="heading"><?php echo $this->escapeHtml($work->getName()); ?></h1>
<div class="">
    <?php echo $work->getDescription(); ?>
</div>
<hr>
<ul class="product-soc">
    <li><a href=""><i class="fa fa-facebook product-icon"></i></a></li>
    <li>
        <a target="_blank" href="https://www.instagram.com/p/Btn1QtIHTAM/?utm_source=ig_share_sheet&igshid=771djgdckxo3">
            <i class="fa fa-instagram product-icon"></i>
        </a>
    </li>
</ul>