<?php
/** @var Core\Entity\Product $product */
$product = $this->product;
?>
<h1 class="heading"><?php echo $this->escapeHtml($product->getName()); ?></h1>
<div class="product-str">
    <span class="name">Габариты (ШхВxГ):</span>
    <span class="numb">
        <?php echo sprintf('%sx%sx%s мм', $product->getWeight(), $product->getHeight(), $product->getDepth()); ?>
    </span>
</div>
<div class="product-str">
    <span class="name">Спальное место:</span>
    <span class="numb">140х200 см</span>
</div>
<div class="product-str">
    <span class="name">Объем бельевицы:    </span>
    <span class="numb">210 литров</span>
</div>
<div class="product-str">
    <span class="name">Материал обивки:    </span>
    <span class="numb">Экокожа</span>
</div>
<div class="product-str">
    <span class="name">Цвет:</span>
    <span class="numb">Бежевый</span>
</div>
<div class="product-important">
    <span class="name">В наличие на складе</span>
    <span class="numb"><i class="fa fa-check"></i></span>
</div>
<div class="product-important">
    <span class="name">Стоимость</span>
    <span class="numb">12000 Р</span>
</div>
<div class="product-str">
    <span class="name">Доставка на дом</span>
    <span class="numb">Бесплатно</span>
</div>
<hr>
<ul class="product-soc">
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-vk"></i></a></li>
</ul>
<a href="#small-dialog" class="popup-with-zoom-anim button">заказать по телефону</a>