<?php
/** @var Core\Entity\Product $product */
$product = $this->product;
?>
<h1 class="heading"><?php echo $this->escapeHtml($product->getName()); ?></h1>

<?php if ($product->getService()->isSofa() || $product->getService()->isBed()): ?>
    <p style="font-style: italic">все размеры и механизмы оговариваются с клиентом</p>
    <?php echo $this->partial('application/product/partials/details/sofa', ['product' => $product]); ?>
<?php else: ?>
    <p style="font-style: italic">все размеры, материал обивки, цвет ног и прочее согласовывается с заказчиком</p>
    <div class="product-str">
        <span class="name">Габариты (ШхВxГ):</span>
        <span class="numb">
        <?php echo sprintf('%sx%sx%s мм', 1, 1, 1); ?>
    </span>
    </div>
<?php endif; ?>

<div class="product-important">
    <span class="name">Стоимость</span>
    <span class="numb"><?php echo number_format($product->getPrice(), 2); ?> Р</span>
</div>
<?php if ($product->getService()->isSofa() || $product->getService()->isBed()): ?>
    <div class="product-str">
        <span class="name">Доставка по Минску</span>
        <span class="numb">Бесплатно</span>
    </div>
<?php endif; ?>

<hr>
<ul class="product-soc">
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li>
        <a target="_blank"
           href="https://www.instagram.com/p/Btn1QtIHTAM/?utm_source=ig_share_sheet&igshid=771djgdckxo3">
            <i class="fa fa-instagram"></i>
        </a>
    </li>
</ul>