<?php
/** @var Core\Entity\Product $product */
$product = $this->product;
?>
<h1 class="heading"><?php echo $this->escapeHtml($product->getName()); ?></h1>

<?php if ($product->getService()->isSofa()): ?>
    <?php echo $this->partial('application/product/partials/details/sofa', ['product' => $product]); ?>
<?php endif;?>

<div class="product-important">
    <span class="name">В наличие на складе</span>
    <span class="numb"><i class="fa fa-check"></i></span>
</div>
<div class="product-important">
    <span class="name">Стоимость</span>
    <span class="numb">12000 Р</span>
</div>
<div class="product-str">
    <span class="name">Доставка на дом</span>
    <span class="numb">Бесплатно</span>
</div>
<hr>
<ul class="product-soc">
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-vk"></i></a></li>
</ul>
<a href="#small-dialog" class="popup-with-zoom-anim button">заказать по телефону</a>