<?php
$paginator = $this->paginator;
?>
<?php if ($paginator->getCurrentItemCount()) : ?>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-md-1">#</th>
                    <th class="col-md-2"><?php echo $this->translate('E-mail') ?></th>
                    <th class="col-md-3"><?php echo $this->translate('Full Name') ?></th>
                    <th class="col-md-1"><?php echo $this->translate('Status') ?></th>
                    <th class="col-md-2"><?php echo $this->translate('Updated At') ?></th>
                    <th class="col-md-3"><?php echo $this->translate('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($paginator as $user) : ?>
                    <?php echo $this->partial('admin/user/partials/item', ['user' => $user]); ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->partial('core/partials/paginator/paginator', ['paginator' => $paginator]); ?>
<?php else: ?>
    <p class="small"><?php echo $this->translate('Users not found.'); ?></p>
<?php endif; ?>