<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin Area</title>

    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('libs/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('libs/metisMenu/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('libs/bootstrap/css/bootstrap.min.css'));
    ?>

    <?php echo $this->headScript()
        ->appendFile($this->basePath('libs/jquery/jquery.min.js'), 'text/javascript')
    ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="<?php echo $this->url('home'); ?>" target="_blanc" class="navbar-brand">
                    <img src="<?php echo $this->basePath('img/logo.png') ?>" width="60px">
                </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <!-- <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li> -->
                    </ul>
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!-- li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                        </li> -->
                        <li>
                            <a href="<?php echo $this->url('admin_dashboard', ['action' => 'index']) ?>">
                                <i class="fa fa-dashboard fa-fw"></i>
                                <?php echo $this->translate('Dashboard') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('admin_product', ['action' => 'index']) ?>">
                                <i class="fa fa-list"></i>
                                <?php echo $this->translate('Catalog') ?>
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->url('admin_product', ['action' => 'index'])?>">
                                        <?php echo $this->translate('Manage Products') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('admin_product_category', ['action' => 'index'])?>">
                                        <?php echo $this->translate('Categories') ?>
                                    </a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php echo $this->url('admin_work', ['action' => 'index']) ?>">
                                <i class="fa fa-briefcase"></i>
                                <?php echo $this->translate('Our Works') ?>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->url('admin_work', ['action' => 'index'])?>">
                                        <?php echo $this->translate('Manage Works') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('admin_work_category', ['action' => 'index'])?>">
                                        <?php echo $this->translate('Categories') ?>
                                    </a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php echo $this->url('admin_news', ['action' => 'index']) ?>">
                                <i class="fa fa-newspaper-o"></i>
                                <?php echo $this->translate('News') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('admin_page', ['action' => 'index']) ?>">
                                <i class="fa fa-file-text-o"></i>
                                <?php echo $this->translate('Static Pages') ?>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('admin_setting', ['action' => 'index']) ?>">
                                <i class="fa fa-cog"></i>
                                <?php echo $this->translate('Settings') ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <?php echo $this->content ?>
        </div>
    </div>
    <!-- /#wrapper -->
    <?php echo $this->inlineScript()
        ->offsetSetFile(2, $this->basePath('libs/bootstrap/js/bootstrap.min.js'), 'text/javascript')
        ->offsetSetFile(3, $this->basePath('libs/metisMenu/metisMenu.min.js'), 'text/javascript')
        ->offsetSetFile(4, $this->basePath('js/sb-admin-2.js'), 'text/javascript')
    ?>
</body>
</html>
