<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $this->translate('Admin Area'); ?></title>

    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('libs/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('libs/metisMenu/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('libs/bootstrap/css/bootstrap.min.css'));
    ?>

    <?php echo $this->headScript()
        ->appendFile($this->basePath('libs/jquery/jquery.min.js'), 'text/javascript')
    ?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<?php echo $this->content ?>
    <!-- /#wrapper -->
    <?php echo $this->inlineScript()
        ->offsetSetFile(2, $this->basePath('libs/bootstrap/js/bootstrap.min.js'), 'text/javascript')
        ->offsetSetFile(3, $this->basePath('libs/metisMenu/metisMenu.min.js'), 'text/javascript')
        ->offsetSetFile(4, $this->basePath('js/sb-admin-2.js'), 'text/javascript')
    ?>
</body>
</html>
