<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->translate('Pages') ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate('Pages') ?>
            </div>
            <!-- .panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    
                </div>
            </div>
            <!-- .panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>