<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <?php echo $this->translate('Please Sign In') ?>
                    </h3>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form) ?>
                        <fieldset>
                            <div class="no-display">
                                <?php echo $this->formElement($form->get('redirect_url')); ?>
                                <?php echo $this->formElement($form->get('csrf')); ?>
                            </div>

                            <?php 
                                $element = $form->get('email');
                                $element->setAttributes(['class' => 'form-control', 'placeholder' => $element->getLabel()]);
                            ?>
                            <div class="form-group<?php echo $element->getMessages() ? ' has-error' : '';?>">
                                <label><?php echo $this->formLabel($element); ?></label>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                                <!-- <p class="help-block">Example block-level help text here.</p> -->
                            </div>

                            <?php 
                                $element = $form->get('password');
                                $element->setAttributes(['class' => 'form-control', 'placeholder' => $element->getLabel()]);
                            ?>
                            <div class="form-group<?php echo $element->getMessages() ? ' has-error' : '';?>">
                                <label><?php echo $this->formLabel($element); ?></label>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                                <!-- <p class="help-block">Example block-level help text here.</p> -->
                            </div>

                            <div class="checkbox">
                                <label>
                                    <?php echo $this->formElement($form->get('remember_me')); ?> 
                                    <?php echo $this->translate('Remember Me') ?>
                                </label>
                            </div>

                            <button class="btn btn-lg btn-primary btn-block" type="submit">
                                <?php echo $this->translate('Sign in')?>
                            </button>
                        </fieldset>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
</div>