<?php
/** @var ArrayCollection $categories */
$categories = $this->categories;
/** @var Core\Entity\OurWorkCategory $curentCategory */
$curentCategory = $this->curentCategory;
?>
<div class="breadcrumbs breadcrumbs-catalog">
    <div class="container">
        <div class="row">
            <ul>
                <li>
                    <a href="<?php echo $this->url('application_work_list'); ?>">
                    <?php echo $this->translate('Наши работы') ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<section id="works">
    <div class="container">
        <div class="row">
            <?php echo $this->partial('application/work/partials/sidebar', ['categories' => $categories, 'curentCategory' => $curentCategory]); ?>
            
            <div class="col-md-10 col-xs-9 catatolog-block works-block">
                <?php if (!$curentCategory): ?>
                <h1 class="heading"><?php echo $this->translate('Наши работы') ?></h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
                <?php endif; ?>
                <?php echo $this->partial('application/work/partials/items', ['categories' => $categories, 'curentCategory' => $curentCategory]); ?>
            </div>
        </div>
    </div>
</section>