<div class="breadcrumbs breadcrumbs-product">
    <div class="container">
        <div class="row">
            <ul>
                <li><a href="<?php echo $this->url('application_catalog'); ?>">Каталог</a></li>
                <li><a href="<?php echo $this->url('application_work_list'); ?>">Наши работы</a></li>
                <li><a href="#">Бар Клевер</a></li>
            </ul>
        </div>
    </div>
</div>
<section id="work">
    <div class="container">
        <div class="row">
            <div class="col-md-8 product-item-left">
                <div class="section-gallery fotorama" data-nav="thumbs" data-thumbwidth="110.5" data-thumbheight="66" data-thumbmargin="10" data-thumbborderwidth="4">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                    <img src="<?php echo $this->basePath('img/work-image.png') ?>" alt="">
                </div>
            </div>
            <div class="col-md-4 product-item-right">
                <h1 class="heading">Бар Клевер</h1>
                <div class="product-important">
                    <span class="name">Стоимость</span>
                    <span class="numb">100 000 Р</span>
                </div>
                <div class="work-str">
                    <span class="head">Комплектация:</span>
                    <span class="name">Диваны</span>
                    <span class="numb">10 шт.</span><br>
                    <span class="name">Барные стулья</span>
                    <span class="numb">20 шт.</span><br>
                    <span class="name">Еще что-то</span>
                    <span class="numb">20 шт.</span><br>
                </div>
                <div class="work-str">
                    <span class="head">Материалы:</span>
                    <span class="name">Первый</span>
                    <span class="numb"> </span><br>
                    <span class="name">Второй</span>
                    <span class="numb"> </span><br>
                    <span class="name">Третий</span>
                    <span class="numb"> </span><br>
                </div>
                <hr>
                <ul class="product-soc">
                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                    <li><a href=""><i class="fa fa-vk"></i></a></li>
                </ul>
            </div>
        </div>
        <div class="row bonus-buy">
            <div class="container">
                <h2>Другие работы...</h2>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
                <div class="col-md-4 hidden-sm hidden-xs">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>