<?php
/** @var Core\Entity\OurWork $work */
$work = $this->work;
?>
<div class="breadcrumbs breadcrumbs-product">
    <div class="container">
        <div class="row">
            <ul>
                <li>
                    <a href="<?php echo $this->url('application_catalog'); ?>">
                    <?php echo $this->translate('Каталог') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application_work_list'); ?>">
                    <?php echo $this->translate('Наши работы') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application_work_view', ['slug' => $work->getSlug()]) ?>">
                    <?php echo $this->escapeHtml($work->getName()); ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<section id="work">
    <div class="container">
        <div class="row">
            <div class="col-md-8 product-item-left">
                <?php if ($work->getImages()->count() > 0): ?>
                <div class="section-gallery fotorama" data-nav="thumbs" data-thumbwidth="110.5" data-thumbheight="66" data-thumbmargin="10" data-thumbborderwidth="4">
                    <?php foreach ($work->getImages() as $image): ?>
                        <img src="<?php echo $image->getRelativeUrl('medium'); ?>" alt="<?php echo $this->escapeHtml($work->getName()); ?>">
                    <?php endforeach;?>
                </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4 product-item-right">
                <?php echo $this->partial('application/work/partials/details', ['work' => $work]); ?>
            </div>
        </div>
        <!-- <div class="row bonus-buy">
            <div class="container">
                <h2>Другие работы...</h2>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
                <div class="col-md-4 hidden-sm hidden-xs">
                    <a href="" class="catalog-item">
                        <img src="<?php echo $this->basePath('img/bonus-work.png') ?>" alt="">
                        <hr>
                        <div class="name">Магазин Армония</div>
                    </a>
                </div>
            </div>
        </div> -->
    </div>
</section>