<?php
    $element = $this->form->get($this->name);
    $class = 'form-control';
    if (isset($this->class)) {
        $class .= ' ' . $this->class;
    }
    $element->setAttributes(['class' => $class, 'placeholder' => $element->getLabel()]);
?>
<div class="form-group<?php echo $element->getMessages() ? ' has-error' : '';?>">
    <label><?php echo $this->formLabel($element); ?></label>
    <?php echo $this->formElement($element); ?>
    <?php echo $this->formElementErrors()->render($element); ?>
    <!-- <p class="help-block">Example block-level help text here.</p> -->
</div>