<?php
$paginator = $this->paginator;
?>
<?php if ($paginator->getCurrentItemCount()) : ?>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-md-1">#</th>
                    <th class="col-md-4"><?php echo $this->translate('Name'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('Status'); ?></th>
                    <th class="col-md-2"><?php echo $this->translate('Updated At'); ?></th>
                    <th class="col-md-3"><?php echo $this->translate('Actions'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($paginator as $category) : ?>
                    <?php echo $this->partial('admin/our-work-category/partials/item', ['category' => $category]); ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->partial('core/partials/paginator/paginator', ['paginator' => $paginator]); ?>
<?php else: ?>
    <p class="small"><?php echo $this->translate('Categories not found.'); ?></p>
<?php endif; ?>