<?php
/** @var Core\Entity\Product $product */
$product = $this->product;
?>
<div class="breadcrumbs breadcrumbs-product">
    <div class="container">
        <div class="row">
            <ul>
                <li><a href="<?php echo $this->url('application_catalog')?>"><?php echo $this->translate('Каталог'); ?></a></li>
                <li>
                    <a href="<?php echo $this->url('application_catalog', ['action' => 'view', 'slug' => $product->getCategory()->getSlug()])?>">
                        <?php echo $this->escapeHtml($product->getCategory()->getName()); ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('application_product', ['action' => 'view', 'slug' => $product->getSlug()])?>">
                        <?php echo $this->escapeHtml($product->getName()); ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<section id="product">
    <div class="container">
        <div class="row">
            <div class="col-md-8 product-item-left">
                <?php if (count($product->getImages(true)) > 0): ?>
                <div class="section-gallery fotorama" data-nav="thumbs" data-thumbwidth="110.5" data-thumbheight="66" data-thumbmargin="10" data-thumbborderwidth="4" data-allowfullscreen="true">
                    <?php foreach ($product->getImages(true) as $image): ?>
                        <img src="<?php echo $image->getRelativeUrl('medium'); ?>" alt="<?php echo $product->getName(); ?>">
                    <?php endforeach;?>
                </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4 product-item-right">
                <?php echo $this->partial('application/product/partials/details', ['product' => $product]); ?>
            </div>
        </div>
        <div class="row">
            <div class="product-text">
                <ul>
                    <li class="li-text li-active"><?php echo $this->translate('Описание'); ?></li>
                    <?php if ($product->getService()->isSofa() || $product->getService()->isBed()): ?>
                        <?php if (count($product->getSchemas())): ?><li class="li-size"><?php echo $this->translate('Размеры'); ?></li><?php endif; ?>
                    <?php endif; ?>
                </ul>
                <div class="text"><?php echo $product->getDescription(); ?></div>
                <?php if ($product->getService()->isSofa() || $product->getService()->isBed()): ?>
                    <?php if (count($product->getSchemas())): ?>
                        <div class="size fotorama" data-maxwidth="100%" data-maxheight="500" data-allowfullscreen="false">
                            <?php foreach ($product->getSchemas() as $schema): ?>
                                <img src="<?php echo $schema->getRelativeUrl('medium'); ?>" />
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($conversionType = $product->getConversionType()): ?>
                        <p class="complect"><img src="<?php echo $conversionType->getThumbnail()->getRelativeUrl(); ?>" /></p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
        <!-- <div class="row bonus-buy">
            <div class="container">
                <h2>С этим товаром покупают также...</h2>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="img/catalog/4.png" alt="">
                        <hr>
                        <div class="name">Глостер</div>
                        <div class="price">12000 р</div>
                    </a>
                </div>
                <div class="col-md-4 col-xs-6">
                    <a href="" class="catalog-item">
                        <img src="img/catalog/5.png" alt="">
                        <hr>
                        <div class="name">Глостер</div>
                        <div class="price">12000 р</div>
                    </a>
                </div>
                <div class="col-md-4 hidden-sm hidden-xs">
                    <a href="" class="catalog-item">
                        <img src="img/catalog/6.png" alt="">
                        <hr>
                        <div class="name">Глостер</div>
                        <div class="price">12000 р</div>
                    </a>
                </div>
            </div>
        </div> -->
    </div>
</section>