<div class="breadcrumbs breadcrumbs-product">
	<div class="container">
		<div class="row">
			<ul>
				<li><a href="<?php echo $this->url('application_catalog')?>">Каталог</a></li>
				<li><a href="<?php echo $this->url('application_catalog')?>">Диваны для дома</a></li>
				<li><a href="<?php echo $this->url('application_catalog')?>">Брабус</a></li>
			</ul>
		</div>
	</div>
</div>
<section id="product">
	<div class="container">
		<div class="row">
			<div class="col-md-8 product-item-left">
				<div class="section-gallery fotorama" data-nav="thumbs" data-thumbwidth="110.5" data-thumbheight="66" data-thumbmargin="10" data-thumbborderwidth="4">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
					<img src="img/product.png" alt="">
				</div>

			</div>
			<div class="col-md-4 product-item-right">
				<h1 class="heading">Диван Брабус</h1>
				<div class="product-str">
					<span class="name">Габариты (ШхГхВ):</span>
					<span class="numb">241х93х86 см</span>
				</div>
				<div class="product-str">
					<span class="name">Спальное место:</span>
					<span class="numb">140х200 см</span>
				</div>
				<div class="product-str">
					<span class="name">Объем бельевицы:	</span>
					<span class="numb">210 литров</span>
				</div>
				<div class="product-str">
					<span class="name">Материал обивки:	</span>
					<span class="numb">Экокожа</span>
				</div>
				<div class="product-str">
					<span class="name">Цвет:</span>
					<span class="numb">Бежевый</span>
				</div>
				<div class="product-important">
					<span class="name">В наличие на складе</span>
					<span class="numb"><i class="fa fa-check"></i></span>
				</div>
				<div class="product-important">
					<span class="name">Стоимость</span>
					<span class="numb">12000 Р</span>
				</div>
				<div class="product-str">
					<span class="name">Доставка на дом</span>
					<span class="numb">Бесплатно</span>
				</div>
				<hr>
				<ul class="product-soc">
					<li><a href=""><i class="fa fa-facebook"></i></a></li>
					<li><a href=""><i class="fa fa-vk"></i></a></li>
				</ul>
				<a href="#small-dialog" class="popup-with-zoom-anim button">заказать по телефону</a>
			</div>

		</div>
		<div class="row">
			<div class="product-text">
				<ul>
					<li class="li-text li-active">Описание</li>
					<li class="li-size">Размеры</li>
					<li class="li-complect">Комплектация</li>
				</ul>
				<p class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo illum quibusdam accusamus quas eaque rem nemo, quaerat tenetur officiis nulla ad fugit soluta in itaque natus dolor libero optio dolores!</p>
				<p class="size">ipsum dolor sit amet, consectetur adipisicing elit. Quo illum quibusdam accusamus quas eaque rem nemo, quaerat tenetur officiis nulla ad fugit soluta in itaque natus dolor libero optio dolores!</p>
				<p class="complect"> dolor sit amet, consectetur adipisicing elit. Quo illum quibusdam accusamus quas eaque rem nemo, quaerat tenetur officiis nulla ad fugit soluta in itaque natus dolor libero optio dolores!</p>
				
			</div>
		</div>
		<div class="row bonus-buy">
			<div class="container">
				<h2>С этим товаром покупают также...</h2>
				<div class="col-md-4 col-xs-6">
					<a href="" class="catalog-item">
						<img src="img/catalog/4.png" alt="">
						<hr>
						<div class="name">Глостер</div>
						<div class="price">12000 р</div>
					</a>
				</div>
				<div class="col-md-4 col-xs-6">
					<a href="" class="catalog-item">
						<img src="img/catalog/5.png" alt="">
						<hr>
						<div class="name">Глостер</div>
						<div class="price">12000 р</div>
					</a>
				</div>
				<div class="col-md-4 hidden-sm hidden-xs">
					<a href="" class="catalog-item">
						<img src="img/catalog/6.png" alt="">
						<hr>
						<div class="name">Глостер</div>
						<div class="price">12000 р</div>
					</a>
				</div>
			</div>
		</div>
	</div>
</section>