<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <ul>
                <li><a href="#">Рассрочка</a></li>
            </ul>
        </div>
    </div>
</div>
<section id="installment">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-push-2 col-xs-12">
                <h1 class="heading">Кухни в рассрочку на 36 месяцев</h1>
                В салонах Мастер Мебель можно купить кухню в рассрочку сроком от 3 до 36 месяцев.
                Рассрочку можно оформить через банк или оплатить покупку картами рассрочки.
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-push-2 col-xs-12">
                <h2 class="heading installment-category-header">Рассрочка через банк</h2>
                <ul class="installment-list">
                    <li><span class="bank-name">Беларуссбанк</span> от 3 до 36 месяцев</li>
                    <li><span class="bank-name">Паритетбанк</span> от 3 до 36 месяцев</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-push-2 col-xs-12">
                <h2 class="heading installment-category-header">Рассрочка по картам</h2>
                <ul class="installment-list">
                    <li><span class="bank-name">Халва</span> от МТБанка на 3 и 6 месяцев</li>
                    <li><span class="bank-name">Карта покупок</span> от Белгазпромбанка на 6 месяцев</li>
                    <li><span class="bank-name">SMART карта</span> от Банка Москвы-Минск на 5 месяцев</li>
                    <li><span class="bank-name">Магнит</span> от Беларусбанка на 5 месяцев</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-push-2 col-xs-12">
                <p><span style="color: deeppink">На бытовую технику</span> действует рассрочка до 12 месяцев от Беларусбанка
                    и Паритетбанка.</p>
            </div>
        </div>

    </div>
</section>