<?php
/** @var ArrayCollection $categories */
$categories = $this->categories;
/** @var Core\Entity\Category $curentCategory */
$curentCategory = $this->curentCategory;
?>
<div class="breadcrumbs breadcrumbs-catalog">
    <div class="container">
        <div class="row">
            <ul>
                <li>
                    <a href="<?php echo $this->url('application_catalog')?>">
                        <?php echo $this->translate('Каталог') ?>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<section id="catalog">
    <div class="container">
        <div class="row">
            <?php echo $this->partial('application/catalog/partials/sidebar', ['categories' => $categories, 'curentCategory' => $curentCategory]); ?>
    
            <div class="col-md-10 col-xs-9 catatolog-block">
                <?php echo $this->partial('application/catalog/partials/items', ['categories' => $categories, 'curentCategory' => $curentCategory]); ?>
            </div>
        </div>
    </div>
</section>