<?php
$paginator = $this->paginator;
?>
<?php if ($paginator->getCurrentItemCount()) : ?>
    <div class="table-responsive">
        <table class="table table-hover w-100">
            <thead>
            <tr>
                <th class="col-md-1">#</th>
                <th class="col-md-2"><?php echo $this->translate('Name'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Rate Value'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Created At'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Updated At'); ?></th>
                <th class="col-md-3"><?php echo $this->translate('Actions'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($paginator as $moneyRate) : ?>
                <?php echo $this->partial('admin/money-rate/partials/item', ['moneyRate' => $moneyRate]); ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->partial('core/partials/paginator/paginator', ['paginator' => $paginator]); ?>
<?php else: ?>
    <p class="small"><?php echo $this->translate('Money rates not found.'); ?></p>
<?php endif; ?>