<?php
    /** @var Application\View\Helper\Layout $layoutHelper */
    $layoutHelper = $this->layoutHelper();
    if (!$categories = $this->categories) {
        $categories = $layoutHelper->getActiveCategories();
    }
    if (!$ourWorkCategories = $this->ourWorkCategories) {
        $ourWorkCategories = $layoutHelper->getOurWorkCategories();
    }

    echo $this->doctype();
?>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('filini')->setSeparator(' - ')->setAutoEscape(false); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style>body { opacity: 0; overflow-x: hidden; } html { background-color: #fff; }</style>
    <!-- Le styles -->
    <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/main.min.css'));
        // ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        // ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?php // echo $this->headScript()
        //->prependFile($this->basePath('js/bootstrap.min.js'))
    ?>
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <!--Блок для 724px-->
                <div class="col-sm-12  hidden-md hidden-lg table-phone">
                    <div class="phone">
                        <i class="fa fa-mobile"></i> 
                        <a href="tel:+375447112336">+375&nbsp;44&nbsp;711-23-36</a>
                    </div>
                    <a href="#small-dialog" class="popup-with-zoom-anim button">
                        заказать звонок
                    </a>
                </div>
                <!--Конец Блок для 724px-->
                <div class="col-md-2 col-sm-2 col-xs-2">
                    <a href="<?php echo $this->url('home'); ?>">
                        <img src="<?php echo $this->basePath('img/logo.jpg'); ?>" alt="" class="logo">
                    </a>
                </div>
                <div class="col-md-7 col-sm-9 col-xs-9">
                    <nav>
                        <ul>
                            <li><a href="<?php echo $this->url('home')?>">Главная</a></li>
                            <li><a href="<?php echo $this->url('application_catalog')?>">Каталог</a></li>
                            <li><a href="<?php echo $this->url('application_work_list')?>">Наши работы</a></li>
                            <li><a href="<?php echo $this->url('application_designers')?>">Дизайнерам</a></li>
                            <li><a href="<?php echo $this->url('application_contact')?>">Контакты</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1 mobile-lang" >
                    <ul class="lang">
                        <li><a href="<?php echo $this->url('home'); ?>" class="active">ru</a></li>
                        <li><a href="#">en</a></li>
                    </ul>
                </div>
                <!--Блок для 1170px и выше-->
                <div class="col-md-2 col-xs-5 mobile-phone">
                    <div class="phone">
                        <i class="fa fa-mobile"></i>
                        <a href="tel:+375447112336">+375&nbsp;44&nbsp;711-23-36</a>
                    </div>
                    <a href="#small-dialog" class="popup-with-zoom-anim button">заказать звонок</a>
                    <img src="<?php echo $this->basePath('img/menu.jpg'); ?>" alt="" class="hidden-lg hidden-md hidden-sm mobile-icon">
                </div>
                <!--Конец Блок для 1170px и выше-->
                <!--Мобильное меню-->
                <div class="shadow-menu"></div>
                <div class="mobile-nav">
                    <nav>
                        <ul>
                            <li><a href="<?php echo $this->url('home')?>">Главная</a></li>
                            <li><a href="<?php echo $this->url('application_catalog')?>">Каталог</a></li>
                            <li><a href="<?php echo $this->url('application_work_list')?>">Наши работы</a></li>
                            <li><a href="<?php echo $this->url('application_designers')?>">Дизайнерам</a></li>
                            <li><a href="<?php echo $this->url('application_contact')?>">Контакты</a></li>
                        </ul>
                    </nav>
                    <span class="close-menu">x</span>
                    <!--Конец мобильное меню-->
                </div>
            </div>
        </div>

        <!-- dialog itself, mfp-hide class is required to make dialog hidden -->
        <div id="small-dialog" class="zoom-anim-dialog mfp-hide">
            <form action="">
                <input type="text" placeholder="Ваше имя">
                <input type="text" placeholder="Телефон">
                <button class="button">заказать</button>
            </form>
        </div>
    </header>

    <?= $this->content; ?>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-2">
                    <a href="<?php echo $this->url('home'); ?>">
                        <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt="" class="logo">
                    </a>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-4">
                    <strong>Каталог</strong>
                    <nav class="footer-nav">
                        <ul>
                            <?php foreach ($categories as $category): ?>
                                <li>
                                    <a href="<?php echo $this->url('application_catalog') . '/' . $category->getSlug(); ?>">
                                        <?php echo $category->getName(); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-3 col-xs-3">
                    <!-- <strong>Дизайнерам</strong>
                    <nav class="footer-nav">
                        <ul>
                            <li><a href="<?php echo $this->url('application_designers')?>">Модели 2D-3D</a></li>
                            <li><a href="<?php echo $this->url('application_designers')?>">Скачать каталог</a></li>
                        </ul>
                    </nav> -->
                    <strong>Наши работы</strong>
                    <nav class="footer-nav">
                        <ul>
                            <?php foreach ($ourWorkCategories as $ourWorkCategory): ?>
                                <li>
                                    <a href="<?php echo $this->url('application_work_list') . '/' . $ourWorkCategory->getSlug(); ?>">
                                        <?php echo $ourWorkCategory->getName(); ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </nav>
                </div>
                <div class="col-md-3 col-xs-3">
                    <strong>Контакты</strong>
                    <div class="phone">
                        <i class="fa fa-mobile"></i>
                        <a href="tel:+375447112336">+375&nbsp;44&nbsp;711-23-36</a>
                    </div>
                    <div class="phone mail-footer">
                        <i class="fa fa-envelope-o"></i>
                        <a href="mailto:info@filini.by">info@filini.by</a>
                    </div>
                    <!-- <div class="soc-item">
                        <a href="#">
                            <img src="<?php echo $this->basePath('img/icon/1.png'); ?>" alt="">
                        </a>
                        <a href="#">
                            <img src="<?php echo $this->basePath('img/icon/2.png'); ?>" alt="">
                        </a>
                    </div> -->
                </div>
            </div>
        </div>
        <p class="copy">&copy; 2017&ndash;<?php echo date('Y'); ?>. Все права защищены.</p>
    </footer>

    <?php echo $this->inlineScript()
        ->appendFile($this->basePath('js/scripts.min.js'), 'text/javascript')
    ?>
    <script>
        $(function() {

            $(".owl-carousel").owlCarousel({
            items: 1,
            nav: true,
            loop:true,
        });
        });
    </script>
</body>
</html>
