<?php
$paginator = $this->paginator;
?>
<?php if ($paginator->getCurrentItemCount()) : ?>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th class="col-md-1">#</th>
                <th class="col-md-2"><?php echo $this->translate('Title'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Description'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Status'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Created At'); ?></th>
                <th class="col-md-1"><?php echo $this->translate('Updated At'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($paginator as $promotion) : ?>
                <?php echo $this->partial('admin/promotion/partials/item', ['promotion' => $promotion]); ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->partial('core/partials/paginator/paginator', ['paginator' => $paginator]); ?>
<?php else: ?>
    <p class="small"><?php echo $this->translate('Promotions not found.'); ?></p>
<?php endif; ?>