<?php if ($paginator->getCurrentItemCount()): ?>
<?php 
    $firstItemNumber = $paginator->getPages()->firstItemNumber;
    $lastItemNumber = $paginator->getPages()->lastItemNumber;
    $totalItemCount = $paginator->getPages()->totalItemCount;
?>
<div class="row">
    <div class="col-sm-12"><?php echo sprintf($this->translate('Showing %d to %d of %d entries'), $firstItemNumber, $lastItemNumber, $totalItemCount) ?>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <ul class="pagination">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'core/partials/paginator/sliding'); ?>
        </ul>
    </div>
</div>
<?php endif; ?>