<?php if ($this->pageCount): ?>
    <?php if (isset($this->previous)): ?>
        <li>
            <a href="<?php echo $this->url($this->route, [], ["query" => ["page" => $this->previous]]) ?>"
                 class="previous" data-page="<?php echo $this->previous; ?>">
                <i class="pagination-icn zmdi zmdi-chevron-left"></i>
                <span class="pagination-text"><?php echo $this->translate('Previous'); ?></span>
            </a>
        </li>
    <?php endif;?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url($this->route, [], ["query" => ["page" => $page]]) ?>"
                   class="pagination__item__link" data-page="<?php echo $page; ?>">
                    <?php echo $page; ?>
                </a>
            </li>
        <?php else: ?>
            <li class="active">
                <span class="pagination__item__link disabled"><?php echo $page; ?></span>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
        <li>
             <a href="<?php echo $this->url($this->route, [], ["query" => ["page" => $this->next]]) ?>"
                   class="pagination__item__link next" data-page="<?php echo $this->next; ?>">
                <span class="pagination-text"><?php echo $this->translate('Next'); ?></span>
                <i class="pagination-icn zmdi zmdi-chevron-right"></i>
            </a>
        </li>
    <?php endif;?>
<?php endif;?>
