<?php
/** @var ArrayCollection $videoReviews */
$videoReviews = $this->videoReviews;
?>
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <ul>
                <li><a href="#"> Видео отзывы </a></li>
            </ul>
        </div>
    </div>
</div>
<section id="video-review">
    <div class="container">
        <div class="row">
            <?php echo $this->partial('application/video-review/partials/items', ['videoReviews' => $videoReviews]); ?>
        </div>
    </div>
</section>