<?php
/** @var \Core\Entity\Permission $permission */
$permission = $this->permission;
?>
<tr>
    <td><?php echo $permission->getId(); ?></td>
    <td><?php echo $permission->getName(); ?></td>
    <td><?php echo $permission->getDescription(); ?></td>
    <td><?php echo $permission->getCreatedAt()->format('d M Y, m:i'); ?></td>
    <td>
        <a href="<?php echo $this->url('admin_user_permission', ['action' => 'edit', 'id' => $permission->getId()]) ?>" class="btn btn-primary btn-sm">
            <i class="fa fa-edit"></i>
            <?php echo $this->translate('Edit') ?>
        </a>
        <a href="<?php echo $this->url('admin_user_permission', ['action' => 'remove', 'id' => $permission->getId()]) ?>" class="btn btn-danger btn-sm" onclick="return confirm('Are u sure?');">
            <i class="fa fa-trash-o"></i>
            <?php echo $this->translate('Remove') ?>
        </a>
    </td>
</tr>