<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
$title = $form->getObject()->getId() ? 'Edit Video Reviews' : 'Add Video Reviews';
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?php echo $this->translate('Video Reviews'); ?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->form()->openTag($form); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $this->translate($title); ?>
            </div>
            <!-- .panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        <?php foreach ($form->getElements() as $name => $element): ?>
                            <?php
                            if ($name == 'rateValue') {
                                $element->setLabel('Значение курса');
                            }

                            $element->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => $element->getLabel(),
                            ])->setLabelAttributes([
                                'class' => 'control-label',
                            ]);
                            ?>
                            <div class="form-group<?php echo $element->getMessages() ? ' has-error' : ''; ?>">
                                <label><?php echo $this->formLabel($element); ?>:</label>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>

                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="col-lg-2 hidden"></div>
                </div>
            </div>
            <!-- .panel-body -->

            <!-- .panel-footer -->
            <div class="panel-footer">
                <a href="<?php echo $this->url('admin_video_review') ?>" class="btn btn-default">
                    <i class="fa fa-arrow-left"></i>
                    <?php echo $this->translate('Back'); ?>
                </a>
                <div class="pull-right">
                    <button type="submit" class="btn btn btn-primary">
                        <i class="fa fa-send-o"></i>
                        <?php echo $this->translate('Submit'); ?>
                    </button>
                    <button type="reset" class="btn btn-warning"><?php echo $this->translate('Reset'); ?></button>
                </div>
            </div>
            <!-- /.panel-footer -->
        </div>
        <!-- /.panel -->
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>